### ISSUE TITLE
Not able to find cloudflareauditzones.yaml under logstash foldeer

### ISSUE THREAD

**Issue by 27bharath** [wwalker0307/ElasticFlare#1]
Hi , 

As i was looking for the same to collect cloudflare logs through logpull API , so am referring yours to implement this, but am not getting your steps here and no documentation how should go through to execute. 

If you have a document please send . 

As i configured my logstash and which is now throwing error as it couldnt able to find some files

[2020-09-14T15:43:44,180][ERROR][logstash.filters.translate] Invalid setting for translate filter plugin:

  filter {
    translate {
      # This setting must be a path
      # File does not exist or cannot be opened /dictionaries/cloudflareauditzones.yaml
      dictionary_path => "/dictionaries/cloudflareauditzones.yaml"
      ...
    }
  }
[2020-09-14T15:43:44,276][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline

**Comment by wwalker0307** [comment]
There's a separate script that generates that dictionary under logstash/scripts named CFDictionaries.ps1
