### ISSUE TITLE
CFLogPull.ps1 keeps throwing error during execution even with the right variables defined

### ISSUE THREAD

**Issue by Rajprince2793** [wwalker0307/ElasticFlare#2]
Hi , 

Thanks for sharing this on the forum , I was redirected here from the Elastic forum and was interested in trying this out . 

I was able to run the CFDictionaries script without any issues and pull the zones from my organization ID. But the other script for pulling CFlogs and audit logs keeps throwing error. 

Here is the error I'm getting on PS :

Based on the number of api calls it is making , it looks like it is reaching all my zones under the org ID , but keeps pointing to the Invoke-RestMethod under errors. Is there something I'm missing here ? Appreciate any insight you could give me on this ? Thanks in advance. 

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\anthonyp\Downloads\ElasticFlare-master\ElasticFlare\logstash\scripts\CFLogPull.ps1:55 char:10
+     $R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/z ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by wwalker0307** [comment]
Interesting, by the looks of it, you've properly configured the variables at the top for API Key and email address.  It also looks like you have a number of enterprise licensed zones.  Have you enabled the log retention flag for your zones?  This is something they added since I last updated this script so I don't have a check built-in for it.  You can make the API call yourself or your account rep can go in and enable it for you.

You could also try copy/pasting the first 62 lines into a PowerShell window and then run line 55 with verbose enabled.  This will result in all the same errors as the loop executes.  
```
$R = Invoke-RestMethod @A "https://api.cloudflare.com/client/v4/zones/$z/logs/received?start=$S&end=$E&timestamps=unix&fields=$Fields -Verbose
```

This will cause the last zone lookup it attempted to be printed out in yellow and replace all the variables in the URL with the actual call values.  Copy/Paste that into the ticket, change the value between /zones and /logs though, we don't need your zone id posted on the internet

**Comment by Rajprince2793** [comment]
Thank you for the quick response , that is something I missed. I've assumed our log retention is turned on by default , but I just realized that by making a call to one of our test zones and noticed it .

    "https://api.cloudflare.com/client/v4/zones/xxxxxxxxxxxxxxxxxxxx/logs/received?start=2017-07-18T22:00:00Z&end=2017-07-18T22:01:00Z&count=1&fields=RayID,ClientIP"
Retention is not turned on. Please enable log retention

I will reach out to our admin to work on this as I don't have the access to PUSH requests to enable log retention flags. Thank you for pointing that , hopefully this will be the fix . Will keep you updated on the status. 

Also , is there any other way to get the output error in detail than a generic (400) bad request. Just curious :)

**Comment by wwalker0307** [comment]
Unfortunately I am unaware of an "easy" way to get more detailed information.  The error message `The remote server returned an error: (400) Bad Request.` is the response that PowerShell receives from CloudFlare.  To get a more specific error, diagnostic commands would have to be performed to identify the issue (IE, API call to find account info, then zone information, retention flag, etc...)

The script essentially does this already with logic statements, it just didn't have one to handle unset retention flags.  I'm updating the script in a moment to include a check for the retention flag and an email notification if the flag is not set.

**Comment by Rajprince2793** [comment]
Thanks for your assistance on this. Will follow this thread for future updates or version supports.
